(in-package :vkle-demo)

(defun instance-demo ()
  (init-basic-glfw ()
    (with-instance (instance)
	     (princ "Create Instance Success")
	     (set-key-callback 'key-callback)
	     (set-mouse-button-callback 'mouse-callback)
	     (set-window-size-callback 'window-size-callback)
	     (loop until (window-should-close-p) do (wait-events)))))
